export default {
  namespace: 'modal', // String: Prefix string attached to the class of every element generated by the plugin
  skin: null, // set plugin skin

  content: null, // Set the URL, ID or Class.
  overlay: true, // Show the overlay.
  closeElement: null, // Element ID or Class to close the modal
  effect: 'fadeScale', // fadein | slide | newspaper | fall
  overlaySpeed: 200, // Sets the speed of the overlay, in milliseconds
  effectFallback: 'fade', // set default jquery animate when css3 animation doesn't support
  focus: true, // set focus to form element in content
  errorContent: 'sorry, ajax error.', // set ajax error content
  loadingContent: 'loading...', // set loading content

  closeByEscape: true, // Allow the user to close the modal by pressing 'ESC'.
  closeByOverlayClick: true, // Allow the user to close the modal by clicking the overlay.

  width: null, // Set a fixed total width.
  hieght: null, // Set a fixed total height.

  // Callback API
  onOpen: null, // Callback: function() - Fires when the modal open
  onClose: null // Callback: function() - Fires when the modal close
  //onComplete: null // Callback: function() - Fires when the effect end
};
